name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
# waiting for new re-distributable character animations:
#  deploy-examples:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 22
#
#      - uses: pnpm/action-setup@v2
#        name: Install pnpm
#        with:
#          version: 10
#          run_install: true
#
#      - name: Building
#        run: |
#          pnpm -r generate
#          pnpm -r build
#
#      - name: Deploying
#        run: pnpm -r deploy

  docs:
    uses: pmndrs/docs/.github/workflows/build.yml@v2
    with:
      mdx: 'docs'
      libname: 'viverse'
      base_path: '/viverse/docs'
      icon: '⟁'
      home_redirect: '/getting-started/introduction'
      github: 'https://github.com/pmndrs/viverse'
      discord: 'https://discord.gg/poimandres'

  deploy-docs:
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
          
